name: test_emc2dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - sphinx=8.2.3
  - myst-parser=4.0.1
  - numpy
  - matplotlib
  - jupyter-sphinx
  - sphinx-thebe
  - pip
  - pip:
    - sphinx-material==0.0.36